# Generated by Django 4.2.4 on 2023-08-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_aloud', '0002_readaloud_bookmark_readaloud_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='readaloud',
            name='appeared',
            field=models.IntegerField(default=0),
        ),
    ]
