# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_aloud', '0003_readaloud_appeared'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readaloud',
            options={'ordering': ['-id']},
        ),
    ]
