# Generated by Django 4.2.4 on 2023-10-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_choice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoice',
            name='single',
            field=models.BooleanField(default=False),
        ),
    ]
