# Generated by Django 4.2.4 on 2023-11-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_choice', '0003_remove_multichoice_options_multichoice__options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multichoice',
            old_name='_options',
            new_name='options',
        ),
    ]
