# Generated by Django 4.2.4 on 2023-11-04 05:49

import django.contrib.postgres.fields
from django.db import migrations, models
import utils.fields
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('multi_choice', '0004_rename__options_multichoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoice',
            name='options',
            field=utils.fields.jsonField(default=[], validators=[utils.validators.JsonValidator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multichoice',
            name='right_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
