# Generated by Django 4.2.4 on 2023-11-04 12:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import utils.fields
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multi_choice', '0005_alter_multichoice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('content', models.TextField()),
                ('options', utils.fields.jsonField(validators=[utils.validators.JsonValidator])),
                ('right_options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('prediction', models.BooleanField(default=False)),
                ('single', models.BooleanField(default=False)),
                ('appeared', models.IntegerField(default=0)),
                ('bookmark', models.ManyToManyField(blank=True, related_name='mcr_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
