# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_choice', '0006_multichoicereading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multichoice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='multichoicereading',
            options={'ordering': ['-id']},
        ),
    ]
