# Generated by Django 4.2.4 on 2023-09-01 04:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='media/highlight_summary/%Y/%m/%d/')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=5)),
                ('right_option', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')])),
            ],
        ),
    ]
