# Generated by Django 4.2.4 on 2023-09-01 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('highlight_summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightsummary',
            name='appeared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='highlightsummary',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='hs_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='highlightsummary',
            name='prediction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='highlightsummary',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
