# Generated by Django 4.2.4 on 2023-09-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_summary', '0002_highlightsummary_appeared_highlightsummary_bookmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightsummary',
            name='title',
            field=models.TextField(),
        ),
    ]
