# Generated by Django 4.2.4 on 2023-09-01 05:26

import django.contrib.postgres.fields
from django.db import migrations, models
import practices.highlight_summary.models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_summary', '0003_alter_highlightsummary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightsummary',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=5, validators=[practices.highlight_summary.models.validate_array_length]),
        ),
        migrations.AlterField(
            model_name='highlightsummary',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
