# Generated by Django 4.2.4 on 2023-09-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_summary', '0004_alter_highlightsummary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightsummary',
            name='right_option',
            field=models.TextField(),
        ),
    ]
