# Generated by Django 4.2.7 on 2023-11-05 16:28

from django.db import migrations
import utils.fields
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_summary', '0005_alter_highlightsummary_right_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightsummary',
            name='options',
        ),
        migrations.AddField(
            model_name='highlightsummary',
            name='_options',
            field=utils.fields.jsonField(default={}, validators=[utils.validators.JsonValidator]),
            preserve_default=False,
        ),
    ]
