# Generated by Django 4.2.7 on 2023-11-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_summary', '0006_remove_highlightsummary_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlightsummary',
            old_name='_options',
            new_name='options',
        ),
    ]
