# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_summary', '0007_rename__options_highlightsummary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlightsummary',
            options={'ordering': ['-id']},
        ),
    ]
