# Generated by Django 4.2.7 on 2023-11-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_group_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
