# Generated by Django 4.2.4 on 2023-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
