# Generated by Django 4.2.4 on 2023-10-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_studymaterial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyMaterial',
        ),
    ]
