# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_profile_country_profile_org_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id']},
        ),
    ]
