# Generated by Django 4.2.4 on 2023-10-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_profile_organization_plan_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan',
        ),
    ]
