# Generated by Django 4.2.7 on 2023-12-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_alter_coupon_title_alter_studymaterial_title_and_more'),
        ('management', '0005_purchase_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.coupon'),
        ),
    ]
