# Generated by Django 4.2.7 on 2023-12-13 15:53

import django.contrib.postgres.fields
from django.db import migrations, models
import utils.fields
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_purchase_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('validity', models.IntegerField()),
                ('premium_practice_access', models.BooleanField()),
                ('mocktest_access', models.BooleanField()),
                ('validation', utils.fields.jsonField(validators=[utils.validators.JsonValidator])),
                ('thumbnail', models.ImageField(upload_to='media/package/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('validity', models.IntegerField()),
                ('premium_practice_access', models.BooleanField()),
                ('mocktest_access', models.BooleanField()),
                ('cost', models.IntegerField()),
                ('pre_price', models.IntegerField()),
                ('text', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('thumbnail', models.ImageField(upload_to='media/package/%Y/%m/%d/')),
            ],
        ),
    ]
