# Generated by Django 4.2.7 on 2023-12-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_organizationpackage_studentpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationpackage',
            name='validation',
        ),
    ]
