# Generated by Django 4.2.4 on 2023-10-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_group_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
    ]
