# Generated by Django 4.2.7 on 2023-12-13 18:52

from django.db import migrations
import utils.fields
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_organizationpackage_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpackage',
            name='validation',
            field=utils.fields.jsonField(default={}, validators=[utils.validators.JsonValidator]),
            preserve_default=False,
        ),
    ]
