# Generated by Django 4.2.7 on 2023-12-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_organizationpackage_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='org_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.organizationpackage'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='student_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.studentpackage'),
        ),
    ]
