# Generated by Django 4.2.7 on 2023-12-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_purchase_org_package_purchase_student_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='validation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
