# Generated by Django 4.2.4 on 2023-11-03 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('audio', models.FileField(upload_to='media/short_question/%Y/%m/%d/')),
                ('reference_text', models.TextField()),
                ('prediction', models.BooleanField(default=False)),
                ('appeared', models.IntegerField(default=0)),
                ('bookmark', models.ManyToManyField(blank=True, related_name='sq_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
