# Generated by Django 4.2.4 on 2023-10-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_easy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writeeasy',
            old_name='content',
            new_name='question',
        ),
        migrations.AddField(
            model_name='writeeasy',
            name='reference_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
