# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write_easy', '0002_rename_content_writeeasy_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeeasy',
            options={'ordering': ['-id']},
        ),
    ]
