# Generated by Django 4.2.7 on 2023-11-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retell_sentence', '0001_initial'),
        ('summarize', '0002_summarize_appeared_summarize_bookmark_and_more'),
        ('write_easy', '0002_rename_content_writeeasy_question_and_more'),
        ('read_aloud', '0003_readaloud_appeared'),
        ('short_question', '0001_initial'),
        ('repeat_sentence', '0003_alter_repeatsentence_audio'),
        ('describe_image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittingMockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('summarize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarize.summarize')),
                ('write_essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='write_easy.writeeasy')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingMocktest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('describe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='describe_image.describeimage')),
                ('read_aloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_aloud.readaloud')),
                ('repeat_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repeat_sentence.repeatsentence')),
                ('retell_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retell_sentence.retellsentence')),
                ('short_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='short_question.shortquestion')),
            ],
        ),
    ]
