# Generated by Django 4.2.7 on 2023-11-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_incorrect_word', '0001_initial'),
        ('retell_sentence', '0001_initial'),
        ('describe_image', '0001_initial'),
        ('short_question', '0001_initial'),
        ('repeat_sentence', '0003_alter_repeatsentence_audio'),
        ('missing_word', '0003_rename__options_missingword_options'),
        ('highlight_summary', '0007_rename__options_highlightsummary_options'),
        ('read_aloud', '0003_readaloud_appeared'),
        ('summarize', '0003_summarizespoken'),
        ('write_easy', '0002_rename_content_writeeasy_question_and_more'),
        ('dictation', '0001_initial'),
        ('multi_choice', '0006_multichoicereading'),
        ('blank', '0004_readingblank'),
        ('reorder_paragraph', '0001_initial'),
        ('mocktest', '0002_remove_speakingmocktest_describe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingmocktest',
            name='describe_image',
            field=models.ManyToManyField(related_name='speaking_mocktest', to='describe_image.describeimage'),
        ),
        migrations.AlterField(
            model_name='speakingmocktest',
            name='read_aloud',
            field=models.ManyToManyField(related_name='speaking_mocktest', to='read_aloud.readaloud'),
        ),
        migrations.AlterField(
            model_name='speakingmocktest',
            name='repeat_sentence',
            field=models.ManyToManyField(related_name='speaking_mocktest', to='repeat_sentence.repeatsentence'),
        ),
        migrations.AlterField(
            model_name='speakingmocktest',
            name='retell_sentence',
            field=models.ManyToManyField(related_name='speaking_mocktest', to='retell_sentence.retellsentence'),
        ),
        migrations.AlterField(
            model_name='speakingmocktest',
            name='short_question',
            field=models.ManyToManyField(related_name='speaking_mocktest', to='short_question.shortquestion'),
        ),
        migrations.AlterField(
            model_name='writtingmocktest',
            name='summarize',
            field=models.ManyToManyField(related_name='writting_mocktest', to='summarize.summarize'),
        ),
        migrations.AlterField(
            model_name='writtingmocktest',
            name='write_essay',
            field=models.ManyToManyField(related_name='writting_mocktest', to='write_easy.writeeasy'),
        ),
        migrations.CreateModel(
            name='ReadingMocktest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('dictation', models.ManyToManyField(related_name='reading_mocktest', to='dictation.dictation')),
                ('highlight_incorrect_word', models.ManyToManyField(related_name='reading_mocktest', to='highlight_incorrect_word.highlightincorrectword')),
                ('highlight_summary', models.ManyToManyField(related_name='reading_mocktest', to='highlight_summary.highlightsummary')),
                ('missing_word', models.ManyToManyField(related_name='reading_mocktest', to='missing_word.missingword')),
                ('multi_choice_reading_multi_answer', models.ManyToManyField(related_name='reading_mocktest_multi', to='multi_choice.multichoicereading')),
                ('multi_choice_reading_single_answer', models.ManyToManyField(related_name='reading_mocktest_single', to='multi_choice.multichoicereading')),
                ('reading_balnk', models.ManyToManyField(related_name='reading_mocktest', to='blank.readingblank')),
                ('summarize_spoken', models.ManyToManyField(related_name='reading_mocktest', to='summarize.summarizespoken')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningMocktest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('blank', models.ManyToManyField(related_name='listening_mocktest', to='blank.blank')),
                ('multi_choice_multi_answer', models.ManyToManyField(related_name='listening_mocktest_multi', to='multi_choice.multichoice')),
                ('multi_choice_single_answer', models.ManyToManyField(related_name='listening_mocktest_single', to='multi_choice.multichoice')),
                ('reading_writting_blank', models.ManyToManyField(related_name='listening_mocktest', to='blank.rwblank')),
                ('reorder_paragraph', models.ManyToManyField(related_name='listening_mocktest', to='reorder_paragraph.reorderparagraph')),
            ],
        ),
        migrations.CreateModel(
            name='FullMocktest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('blank', models.ManyToManyField(related_name='full_mocktest', to='blank.blank')),
                ('describe_image', models.ManyToManyField(related_name='full_mocktest', to='describe_image.describeimage')),
                ('dictation', models.ManyToManyField(related_name='full_mocktest', to='dictation.dictation')),
                ('highlight_incorrect_word', models.ManyToManyField(related_name='full_mocktest', to='highlight_incorrect_word.highlightincorrectword')),
                ('highlight_summary', models.ManyToManyField(related_name='full_mocktest', to='highlight_summary.highlightsummary')),
                ('missing_word', models.ManyToManyField(related_name='full_mocktest', to='missing_word.missingword')),
                ('multi_choice_multi_answer', models.ManyToManyField(related_name='full_mocktest_multi', to='multi_choice.multichoice')),
                ('multi_choice_reading_multi_answer', models.ManyToManyField(related_name='full_mocktest_multi_reading', to='multi_choice.multichoicereading')),
                ('multi_choice_reading_single_answer', models.ManyToManyField(related_name='full_mocktest_single_reading', to='multi_choice.multichoicereading')),
                ('multi_choice_single_answer', models.ManyToManyField(related_name='full_mocktest_single', to='multi_choice.multichoice')),
                ('read_aloud', models.ManyToManyField(related_name='full_mocktest', to='read_aloud.readaloud')),
                ('reading_balnk', models.ManyToManyField(related_name='full_mocktest', to='blank.readingblank')),
                ('reading_writting_blank', models.ManyToManyField(related_name='full_mocktest', to='blank.rwblank')),
                ('reorder_paragraph', models.ManyToManyField(related_name='full_mocktest', to='reorder_paragraph.reorderparagraph')),
                ('repeat_sentence', models.ManyToManyField(related_name='full_mocktest', to='repeat_sentence.repeatsentence')),
                ('retell_sentence', models.ManyToManyField(related_name='full_mocktest', to='retell_sentence.retellsentence')),
                ('short_question', models.ManyToManyField(related_name='full_mocktest', to='short_question.shortquestion')),
                ('summarize', models.ManyToManyField(related_name='full_mocktest', to='summarize.summarize')),
                ('summarize_spoken', models.ManyToManyField(related_name='full_mocktest', to='summarize.summarizespoken')),
                ('write_essay', models.ManyToManyField(related_name='full_mocktest', to='write_easy.writeeasy')),
            ],
        ),
    ]
