# Generated by Django 4.2.7 on 2023-12-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0003_alter_speakingmocktest_describe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullmocktest',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='listeningmocktest',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='readingmocktest',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='speakingmocktest',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='writtingmocktest',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
