# Generated by Django 4.2.7 on 2023-12-04 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0006_alter_fullmocktest_blank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullmocktest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 16, 35, 47, 528839, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='listeningmocktest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 16, 35, 47, 524789, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='readingmocktest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 16, 35, 47, 519233, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='speakingmocktest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 16, 35, 47, 514226, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='writtingmocktest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 16, 35, 47, 517612, tzinfo=datetime.timezone.utc)),
        ),
    ]
