# Generated by Django 4.2.4 on 2023-10-27 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repeat_sentence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('audio', models.FileField(upload_to='repeat_sentence/%Y/%m/%d/')),
                ('reference_text', models.TextField()),
                ('prediction', models.BooleanField(default=False)),
                ('appeared', models.IntegerField(default=0)),
                ('bookmark', models.ManyToManyField(blank=True, related_name='rs_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WriteEasy',
        ),
    ]
