# Generated by Django 4.2.4 on 2023-10-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_sentence', '0002_repeatsentence_delete_writeeasy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatsentence',
            name='audio',
            field=models.FileField(upload_to='media/repeat_sentence/%Y/%m/%d/'),
        ),
    ]
