# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_sentence', '0003_alter_repeatsentence_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repeatsentence',
            options={'ordering': ['-id']},
        ),
    ]
