# Generated by Django 4.2.7 on 2023-12-10 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=255)),
                ('val_id', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('store_amount', models.FloatField()),
                ('card_type', models.CharField(max_length=100)),
                ('card_no', models.CharField(max_length=255)),
                ('bank_tran_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('tran_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
