# Generated by Django 4.2.7 on 2023-12-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_amount_alter_payment_bank_tran_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
