# Generated by Django 4.2.7 on 2023-11-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_incorrect_word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightincorrectword',
            name='audio',
            field=models.FileField(upload_to='media/highlight_incorrect/%Y/%m/%d/'),
        ),
    ]
