# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_incorrect_word', '0002_alter_highlightincorrectword_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlightincorrectword',
            options={'ordering': ['-id']},
        ),
    ]
