# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_targetscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examcountdown',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='targetscore',
            options={'ordering': ['-id']},
        ),
    ]
