# Generated by Django 4.2.4 on 2023-10-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_summary', '0005_alter_highlightsummary_right_option'),
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='highlight_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='highlight_summary.highlightsummary'),
        ),
    ]
