# Generated by Django 4.2.3 on 2023-07-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_alter_discussion_like_alter_discussion_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='parent',
        ),
        migrations.AddField(
            model_name='discussion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussion.discussion'),
        ),
    ]
