# Generated by Django 4.2.3 on 2023-07-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_aloud', '0001_initial'),
        ('discussion', '0003_remove_discussion_parent_discussion_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='read_aloud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='read_aloud.readaloud'),
        ),
    ]
