# Generated by Django 4.2.4 on 2023-10-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_discussion_images'),
        ('discussion', '0004_discussion_type'),
    ]

    operations = [
    ]
