# Generated by Django 4.2.4 on 2023-11-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('discussion', '0005_merge_0004_discussion_images_0004_discussion_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='dictation',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='highlight_summary',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='missing_word',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='multi_choice',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='read_aloud',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='summarize',
        ),
        migrations.AddField(
            model_name='discussion',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['content_type', 'object_id'], name='discussion__content_df7738_idx'),
        ),
    ]
