# Generated by Django 4.2.4 on 2023-11-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_summary', '0007_rename__options_highlightsummary_options'),
        ('summarize', '0003_summarizespoken'),
        ('dictation', '0001_initial'),
        ('missing_word', '0003_rename__options_missingword_options'),
        ('read_aloud', '0003_readaloud_appeared'),
        ('multi_choice', '0006_multichoicereading'),
        ('discussion', '0006_remove_discussion_dictation_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discussion',
            name='discussion__content_df7738_idx',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='object_id',
        ),
        migrations.AddField(
            model_name='discussion',
            name='dictation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictation.dictation'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='highlight_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='highlight_summary.highlightsummary'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='missing_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='missing_word.missingword'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='multi_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multi_choice.multichoice'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='read_aloud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='read_aloud.readaloud'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='summarize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summarize.summarize'),
        ),
    ]
