# Generated by Django 4.2.4 on 2023-11-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_incorrect_word', '0001_initial'),
        ('repeat_sentence', '0003_alter_repeatsentence_audio'),
        ('reorder_paragraph', '0001_initial'),
        ('blank', '0003_rwblank'),
        ('retell_sentence', '0001_initial'),
        ('write_easy', '0002_rename_content_writeeasy_question_and_more'),
        ('short_question', '0001_initial'),
        ('describe_image', '0001_initial'),
        ('discussion', '0007_remove_discussion_discussion__content_df7738_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='blank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blank.blank'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='describe_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='describe_image.describeimage'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='highlight_incorrect_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='highlight_incorrect_word.highlightincorrectword'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='read_write_blank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blank.rwblank'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='reorder_paragraph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reorder_paragraph.reorderparagraph'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='repeat_sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repeat_sentence.repeatsentence'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='retell_sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retell_sentence.retellsentence'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='short_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='short_question.shortquestion'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='write_easy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='write_easy.writeeasy'),
        ),
    ]
