# Generated by Django 4.2.4 on 2023-11-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0003_summarizespoken'),
        ('discussion', '0009_discussion_multi_choice_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='summarize_spoken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summarize.summarizespoken'),
        ),
    ]
