# Generated by Django 4.2.7 on 2023-11-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missing_word', '0003_rename__options_missingword_options'),
        ('dictation', '0001_initial'),
        ('highlight_summary', '0007_rename__options_highlightsummary_options'),
        ('multi_choice', '0006_multichoicereading'),
        ('blank', '0003_rwblank'),
        ('summarize', '0003_summarizespoken'),
        ('read_aloud', '0003_readaloud_appeared'),
        ('highlight_incorrect_word', '0001_initial'),
        ('write_easy', '0002_rename_content_writeeasy_question_and_more'),
        ('reorder_paragraph', '0001_initial'),
        ('retell_sentence', '0001_initial'),
        ('repeat_sentence', '0003_alter_repeatsentence_audio'),
        ('describe_image', '0001_initial'),
        ('discussion', '0010_discussion_summarize_spoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='blank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='blank.blank'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='describe_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='describe_image.describeimage'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='dictation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='dictation.dictation'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='highlight_incorrect_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='highlight_incorrect_word.highlightincorrectword'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='highlight_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='highlight_summary.highlightsummary'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='missing_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='missing_word.missingword'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='multi_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='multi_choice.multichoice'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='multi_choice_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='multi_choice.multichoicereading'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='read_aloud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='read_aloud.readaloud'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='read_write_blank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='blank.rwblank'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='reorder_paragraph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='reorder_paragraph.reorderparagraph'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='repeat_sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='repeat_sentence.repeatsentence'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='retell_sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='retell_sentence.retellsentence'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='summarize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='summarize.summarize'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='summarize_spoken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='summarize.summarizespoken'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='write_easy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='write_easy.writeeasy'),
        ),
    ]
