# Generated by Django 4.2.7 on 2023-11-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0004_readingblank'),
        ('discussion', '0011_discussion_read_alter_discussion_blank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='blank_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='blank.readingblank'),
        ),
    ]
