# Generated by Django 4.2.4 on 2023-10-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.CharField(choices=[('prediction', 'Prediction'), ('template', 'Template'), ('study_material', 'Study Material')], max_length=20)),
                ('file', models.FileField(upload_to='study_material/%Y/%m/%d/')),
            ],
            options={
                'unique_together': {('title', 'category')},
            },
        ),
    ]
