# Generated by Django 4.2.4 on 2023-10-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
