# Generated by Django 4.2.7 on 2023-11-07 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_studymaterial_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 7, 17, 55, 0, 762300, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
