# Generated by Django 4.2.7 on 2023-11-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_coupon_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.URLField()),
                ('show_after', models.IntegerField()),
                ('image', models.ImageField(upload_to='promo_banner')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
