# Generated by Django 4.2.7 on 2023-11-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_promobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobanner',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo_banner'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='show_after',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='title',
            field=models.TextField(default='unknown'),
        ),
    ]
