# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_alter_promobanner_active_alter_promobanner_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'ordering': ['-id']},
        ),
    ]
