# Generated by Django 4.2.7 on 2023-12-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_topic_studymaterial_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
