# Generated by Django 4.2.4 on 2023-10-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
    ]
