# Generated by Django 4.2.7 on 2023-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_picture_user_picture_url_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/user'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
