# Generated by Django 4.2.7 on 2023-11-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_picture_user_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='picture_url',
            new_name='image_url',
        ),
    ]
