# Generated by Django 4.2.4 on 2023-10-02 16:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import practices.missing_word.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('audio', models.FileField(upload_to='media/missing_word/%Y/%m/%d/')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=5, validators=[practices.missing_word.models.validate_array_length])),
                ('right_options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=5)),
                ('prediction', models.BooleanField(default=False)),
                ('appeared', models.IntegerField(default=0)),
                ('bookmark', models.ManyToManyField(blank=True, related_name='mw_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
