# Generated by Django 4.2.4 on 2023-11-04 09:16

import django.contrib.postgres.fields
from django.db import migrations, models
import utils.fields
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('missing_word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingword',
            name='options',
        ),
        migrations.AddField(
            model_name='missingword',
            name='_options',
            field=utils.fields.jsonField(default={}, validators=[utils.validators.JsonValidator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missingword',
            name='right_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
