# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missing_word', '0003_rename__options_missingword_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missingword',
            options={'ordering': ['-id']},
        ),
    ]
