# Generated by Django 4.2.3 on 2023-08-05 04:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('read_aloud', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='answer/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('summarize', models.TextField(blank=True, null=True)),
                ('score', models.JSONField(default=dict)),
                ('read_aloud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='read_aloud.readaloud')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
