# Generated by Django 4.2.3 on 2023-07-28 08:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('read_aloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('content_score', models.IntegerField(default=0)),
                ('pronunciation_score', models.IntegerField(default=0)),
                ('fluency_score', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('read_aloud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='read_aloud.readaloud')),
            ],
        ),
    ]
