# Generated by Django 4.2.4 on 2023-08-10 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_alter_answer_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='answer/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['wav'])]),
        ),
    ]
