# Generated by Django 4.2.4 on 2023-09-01 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_summary', '0001_initial'),
        ('answer', '0005_alter_answer_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='highlight_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='highlight_summary.highlightsummary'),
        ),
    ]
