# Generated by Django 4.2.4 on 2023-09-01 10:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0006_answer_answer_answer_highlight_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
