# Generated by Django 4.2.4 on 2023-09-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_choice', '0001_initial'),
        ('answer', '0007_answer_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='multi_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multi_choice.multichoice'),
        ),
    ]
