# Generated by Django 4.2.4 on 2023-10-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missing_word', '0001_initial'),
        ('answer', '0009_answer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='missing_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='missing_word.missingword'),
        ),
    ]
