# Generated by Django 4.2.4 on 2023-10-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0001_initial'),
        ('answer', '0010_answer_missing_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dictation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictation.dictation'),
        ),
    ]
