# Generated by Django 4.2.4 on 2023-10-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('write_easy', '0001_initial'),
        ('answer', '0011_answer_dictation'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='write_easy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='write_easy.writeeasy'),
        ),
    ]
