# Generated by Django 4.2.4 on 2023-10-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_sentence', '0002_repeatsentence_delete_writeeasy'),
        ('answer', '0012_answer_write_easy'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='repeat_sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repeat_sentence.repeatsentence'),
        ),
    ]
