# Generated by Django 4.2.4 on 2023-11-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('short_question', '0001_initial'),
        ('answer', '0014_answer_retell_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='short_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='short_question.shortquestion'),
        ),
    ]
