# Generated by Django 4.2.4 on 2023-11-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('describe_image', '0001_initial'),
        ('answer', '0015_answer_short_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='describe_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='describe_image.describeimage'),
        ),
    ]
