# Generated by Django 4.2.4 on 2023-11-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reorder_paragraph', '0001_initial'),
        ('answer', '0016_answer_describe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reorder_paragraph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reorder_paragraph.reorderparagraph'),
        ),
    ]
