# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('describe_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='describeimage',
            options={'ordering': ['-id']},
        ),
    ]
