# Generated by Django 4.2.4 on 2023-08-12 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summarize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarize',
            name='appeared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summarize',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='summarize_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='summarize',
            name='prediction',
            field=models.BooleanField(default=False),
        ),
    ]
