# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0003_summarizespoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summarizespoken',
            options={'ordering': ['-id']},
        ),
    ]
