# Generated by Django 4.2.7 on 2023-11-12 16:26

import django.contrib.postgres.fields
from django.db import migrations, models
import utils.fields
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('audio', models.FileField(upload_to='media/blank/%Y/%m/%d/')),
                ('sentence', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('answers', utils.fields.jsonField(validators=[utils.validators.JsonValidator])),
            ],
        ),
    ]
