# Generated by Django 4.2.7 on 2023-11-26 16:10

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import utils.fields
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blank', '0003_rwblank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('sentence', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('answers', utils.fields.jsonField(validators=[utils.validators.JsonValidator])),
                ('extra_answers', utils.fields.jsonField(validators=[utils.validators.JsonValidator])),
                ('prediction', models.BooleanField(default=False)),
                ('appeared', models.IntegerField(default=0)),
                ('bookmark', models.ManyToManyField(blank=True, related_name='reading_blank_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
