# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0004_readingblank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blank',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='readingblank',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='rwblank',
            options={'ordering': ['-id']},
        ),
    ]
